services:
  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models
    networks:
      - genai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: no
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./backend/data:/app/backend/data
    networks:
      - genai-network
    restart: no
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx:/etc/nginx/
      - ./nginx/ssl:/ssl/
    networks:
      - genai-network
    restart: no

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "10080:80"
      - "10081:81"
      - "10443:443"
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - genai-network
    restart: no

networks:
  genai-network:
    driver: bridge
    name: genai-network